pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
        jdk "jdk11"
    }

 parameters {
        string(name: 'BRANCH', defaultValue: 'master', description: 'Git branch of the Java project')

    }



    stages {
        stage('compile') {
            steps {
                // Get some code from a GitHub repository
                git branch: "${params.BRANCH}", 
                    url:'https://github.com/matthcol/movieapijava2021.git'

                // Run Maven on a Unix agent.
                sh "mvn clean compile"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }


        }
       
		
		
		stage('test') {
            steps {

                // Run Maven on a Unix agent.
                sh "mvn test"


            }
            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results.
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    
                }
            }

        }
        
		
		
		stage('package') {
            steps {
               

                // Run Maven on a Unix agent.
                sh "mvn -DskipTests package"


            }

            post {
                
                success {

                    archiveArtifacts 'target/*.jar'
					sh "cp target/movieapp.jar /home/srvadmin/RepoArtifacts/`date +%Y%m%d`-movieapp.jar"

                }
            }
        }
		
		stage('publish') {
			steps {
				script {
					withCredentials([sshUserPrivateKey(credentialsId: 'ssh_server_deploy', keyFileVariable: 'identity', passphraseVariable: 'passphrase', usernameVariable: 'userName')]) {
						def remote = [:]
						remote.name = 'test'
						remote.host = '192.168.1.23'
						remote.port = 22
						remote.allowAnyHosts = true
						remote.timoutSec = 3000
						
						remote.user = userName
						remote.identityFile = identity
						remote.passphrase = passphrase

						echo 'deploy artifact'
						sshPut remote: remote, from: "target/movieapp.jar", into: '/home/srvadmin/test'
					}
				}
			}
		}
    }
}
